export const hackathons = [
    {
      id: "1",
      title: "The Docusign Hackathon: Unlocked",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/094/454/datas/medium_square.png",
      organizer: "Docusign",
      timeLeft: "about 6 hours left",
      isOnline: true,
      prizeAmount: 50000,
      participants: 1430,
      startDate: "2025-01-20",
      endDate: "2025-02-27",
      tags: ["Open Ended", "Web", "Enterprise"],
      description: "Join us for an exciting hackathon focused on innovative solutions using Docusign's API...",
      requirements: ["Valid ID proof", "Team size: 2-4 members", "Basic knowledge of web development"],
      rules: [
        "All code must be original",
        "Use of open source libraries is allowed",
        "Projects must be submitted before deadline",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 20, 2025" },
        { phase: "Coding Period", date: "Feb 1-25, 2025" },
        { phase: "Submission", date: "Feb 26, 2025" },
        { phase: "Results", date: "Feb 27, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "2",
      title: "Hack the Future 2025",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/002/935/056/datas/medium_square.jpg",
      organizer: "Tech Innovators",
      timeLeft: "2 days left",
      isOnline: true,
      prizeAmount: 25000,
      participants: 980,
      startDate: "2025-01-15",
      endDate: "2025-02-10",
      tags: ["AI", "Machine Learning", "Startup"],
      description: "Solve real-world problems with AI and machine learning in Hack the Future 2025...",
      requirements: ["Valid ID", "Team size: 3-5", "AI/ML skills"],
      rules: [
        "No plagiarism",
        "Work must be submitted by the end date",
        "Team collaboration is key",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 15, 2025" },
        { phase: "Coding Period", date: "Jan 20-Feb 5, 2025" },
        { phase: "Submission", date: "Feb 9, 2025" },
        { phase: "Results", date: "Feb 10, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "3",
      title: "Open Innovation Challenge",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/120/946/datas/medium_square.png",
      organizer: "Innovative Labs",
      timeLeft: "4 days left",
      isOnline: false,
      prizeAmount: 10000,
      participants: 350,
      startDate: "2025-01-25",
      endDate: "2025-02-05",
      tags: ["Sustainability", "Innovation", "Community"],
      description: "Design solutions for sustainability challenges in this exciting event...",
      requirements: ["Eco-friendly solutions", "Team of 2-4", "Innovative thinking"],
      rules: [
        "Solution must be sustainable",
        "Open-source code encouraged",
        "Presentation of final solution is required",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 25, 2025" },
        { phase: "Coding Period", date: "Jan 26-Feb 3, 2025" },
        { phase: "Submission", date: "Feb 4, 2025" },
        { phase: "Results", date: "Feb 5, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "4",
      title: "SmartCity Hackathon",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/193/397/datas/medium_square.png",
      organizer: "CityTech",
      timeLeft: "7 days left",
      isOnline: false,
      prizeAmount: 15000,
      participants: 500,
      startDate: "2025-02-01",
      endDate: "2025-02-20",
      tags: ["Urban Planning", "IoT", "Smart City"],
      description: "Develop smart city solutions using IoT technologies...",
      requirements: ["Team of 3-5", "IoT expertise", "Urban planning knowledge"],
      rules: [
        "Solutions must be scalable",
        "Use of public APIs is encouraged",
        "Final solution must be implemented in real-time",
      ],
      timeline: [
        { phase: "Registration", date: "Feb 1, 2025" },
        { phase: "Coding Period", date: "Feb 2-15, 2025" },
        { phase: "Submission", date: "Feb 18, 2025" },
        { phase: "Results", date: "Feb 20, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "5",
      title: "Blockchain for Good Hackathon",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/148/763/datas/medium_square.png",
      organizer: "Blockchain Foundation",
      timeLeft: "1 week left",
      isOnline: true,
      prizeAmount: 20000,
      participants: 650,
      startDate: "2025-01-10",
      endDate: "2025-02-17",
      tags: ["Blockchain", "Social Impact", "Decentralization"],
      description: "Build decentralized solutions for social impact using blockchain technology...",
      requirements: ["Blockchain knowledge", "Social impact focus", "Team of 2-5 members"],
      rules: [
        "Projects must be decentralized",
        "Open-source contributions are encouraged",
        "Submission deadline is strict",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 10, 2025" },
        { phase: "Coding Period", date: "Jan 15-Feb 10, 2025" },
        { phase: "Submission", date: "Feb 15, 2025" },
        { phase: "Results", date: "Feb 17, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "6",
      title: "Green Tech Challenge",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/197/558/datas/medium_square.png",
      organizer: "GreenTech",
      timeLeft: "5 days left",
      isOnline: false,
      prizeAmount: 30000,
      participants: 1200,
      startDate: "2025-01-05",
      endDate: "2025-02-10",
      tags: ["Green Technology", "Sustainability", "Innovation"],
      description: "Innovative solutions for a more sustainable future using green technologies...",
      requirements: ["Sustainability focus", "Team of 2-4 members", "Open to all ages"],
      rules: [
        "Solutions must be eco-friendly",
        "Teams should focus on scalability",
        "Final pitch required",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 5, 2025" },
        { phase: "Coding Period", date: "Jan 6-Feb 1, 2025" },
        { phase: "Submission", date: "Feb 5, 2025" },
        { phase: "Results", date: "Feb 10, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "7",
      title: "Tech for Change Hackathon",
      image: "https://example.com/hackathon7.png",
      organizer: "Tech for Change",
      timeLeft: "3 days left",
      isOnline: true,
      prizeAmount: 40000,
      participants: 850,
      startDate: "2025-02-05",
      endDate: "2025-02-28",
      tags: ["Tech for Good", "Innovation", "Social Impact"],
      description: "Create solutions that help bring positive change in the world through technology...",
      requirements: ["Team size: 3-6", "Experience in coding", "Social good focus"],
      rules: [
        "Solutions must focus on social impact",
        "Code should be original",
        "Projects must be submitted on time",
      ],
      timeline: [
        { phase: "Registration", date: "Feb 5, 2025" },
        { phase: "Coding Period", date: "Feb 6-24, 2025" },
        { phase: "Submission", date: "Feb 27, 2025" },
        { phase: "Results", date: "Feb 28, 2025" },
      ],
      
      status: "upcoming",
    },
    {
      id: "8",
      title: "Data Science Challenge",
      image: "https://example.com/hackathon8.png",
      organizer: "Data Science Org",
      timeLeft: "6 days left",
      isOnline: true,
      prizeAmount: 15000,
      participants: 320,
      startDate: "2025-01-30",
      endDate: "2025-02-15",
      tags: ["Data Science", "Machine Learning", "Analytics"],
      description: "Apply data science skills to solve real-world problems using machine learning...",
      requirements: ["Python skills", "Machine Learning experience", "Team of 2-5"],
      rules: [
        "No plagiarism",
        "Machine learning models must be trained on real data",
        "Final submission must be well-documented",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 30, 2025" },
        { phase: "Coding Period", date: "Feb 1-12, 2025" },
        { phase: "Submission", date: "Feb 14, 2025" },
        { phase: "Results", date: "Feb 15, 2025" },
      ],
      
      status: "ended",
    },
    {
      id: "9",
      title: "Women in Tech Hackathon",
      image: "https://example.com/hackathon9.png",
      organizer: "TechWomen",
      timeLeft: "10 days left",
      isOnline: true,
      prizeAmount: 10000,
      participants: 500,
      startDate: "2025-01-15",
      endDate: "2025-02-20",
      tags: ["Diversity", "Women in Tech", "Software Development"],
      description: "Empower women in tech by creating solutions that address key challenges in the industry...",
      requirements: ["Women-led teams", "Tech skills", "Open to all levels"],
      rules: [
        "Projects must be tech-focused",
        "Diversity in team members is encouraged",
        "All submissions must be in by the deadline",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 15, 2025" },
        { phase: "Coding Period", date: "Jan 16-Feb 10, 2025" },
        { phase: "Submission", date: "Feb 15, 2025" },
        { phase: "Results", date: "Feb 20, 2025" },
      ],
      status: "upcoming",
    },
    {
      id: "10",
      title: "AI for Good Hackathon",
      image: "https://example.com/hackathon10.png",
      organizer: "AI for Good",
      timeLeft: "2 weeks left",
      isOnline: false,
      prizeAmount: 25000,
      participants: 1000,
      startDate: "2025-01-25",
      endDate: "2025-02-10",
      tags: ["AI", "Ethical AI", "Social Good"],
      description: "Develop AI-based solutions for social good using ethical AI practices...",
      requirements: ["AI expertise", "Social impact focus", "Team of 3-5 members"],
      rules: [
        "Ethical AI practices must be followed",
        "No harmful algorithms allowed",
        "Projects must be submitted by deadline",
      ],
      timeline: [
        { phase: "Registration", date: "Jan 25, 2025" },
        { phase: "Coding Period", date: "Jan 26-Feb 6, 2025" },
        { phase: "Submission", date: "Feb 8, 2025" },
        { phase: "Results", date: "Feb 10, 2025" },
      ],
      status: "upcoming",
    },
    {
      id: "11",
      title: "Virtual Reality Innovation Hackathon",
      image: "https://example.com/hackathon11.png",
      organizer: "VR Innovators",
      timeLeft: "3 days left",
      isOnline: true,
      prizeAmount: 18000,
      participants: 450,
      startDate: "2025-01-22",
      endDate: "2025-02-10",
      tags: ["Virtual Reality", "Gaming", "Immersive Tech"],
      description: "Create innovative VR experiences that push the boundaries of immersive technology...",
      requirements: ["VR development skills", "Game engine knowledge", "Creative thinking"],
      rules: [
        "Solutions must be VR-based",
        "All code must be original",
        "Submission deadlines must be respected",
      ],
      status: "open",
      timeline: [
        { phase: "Registration", date: "Jan 22, 2025" },
        { phase: "Coding Period", date: "Jan 23-Feb 8, 2025" },
        { phase: "Submission", date: "Feb 9, 2025" },
        { phase: "Results", date: "Feb 10, 2025" },
      ],
    },
  ];
  